DROP TABLE IF EXISTS Departments CASCADE;
CREATE TABLE Departments (
    name TEXT PRIMARY KEY,
    abbr TEXT UNIQUE
);
DROP TABLE IF EXISTS Programs CASCADE;
CREATE TABLE Programs (
    name TEXT PRIMARY KEY,
    abbr TEXT
);